language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

install:
  - cp .env.example .env                                         # Create a new .env file.
  - composer install --no-interaction --prefer-dist --no-suggest # Install dependencies.
  - php artisan key:generate                                     # Generate application key.

script: vendor/bin/phpunit